
      program hello_CUDA
      use cudafor
      integer, parameter :: N = 40000
      real :: x(N), y(N), a
      real, device :: x_d(N), y_d(N)
      type(dim3) :: grid, tBlock

      print*,'Hello CUDA'

      tBlock = dim3(256,1,1)
      grid = dim3(ceiling(real(N)/tBlock%x),1,1)

      print*,'grid, tBlock defined' 

      x = 1.0; y = 2.0; a = 2.0
      !x_d = x
      !y_d = y

      print*,'Data x, y, a loaded to device:',x(1),y(1),a

      end
